sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

matrix:
  include:
    - env: GHCVER=7.8.4
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2
      addons: {apt: {packages: [ghc-7.10.2],sources: [hvr-ghc]}}

before_install:
 - export STACK_YAML=stack-ghc-$GHCVER.yaml
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 # stack
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - export PATH=~/.local/bin:$PATH

install:
 - stack build

script:
  - stack build --test --ghc-options "-Werror"

cache:
  directories:
    - $HOME/.stack
